config/routes.rb
Rails.application.routes.draw do

  root 'information_pages#home'
  get '/help',      to: 'information_pages#help'
  get '/about',     to: 'information_pages#about'
  get '/contact',   to: 'information_pages#contact'
  get '/places',    to: 'places#index'
  get '/addplace',    to: 'places#new'
  post '/addplace',   to: 'places#create'

  resources :places
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/place.rb
class Place < ApplicationRecord

  default_scope -> { order(created_at: :desc) }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/information_pages_controller.rb
class InformationPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController

  def index
    @places = Place.paginate(page: params[:page])
  end

  def new
    @place = Place.new
    @placeholder = 'The right JSON format to add a place is: { "name" : "< name of the place >", "description" : "< the description of the place >", "facebook" : "< the link to facebook > ", "instagram" : "< the link to instagram >" }, so now you can paste your json text here...'
  end

  def create
    begin
      json = params[:place][:json]
      hash_place = JSON.parse(json)
      @place = Place.new(name: hash_place['name'],
                    description: hash_place['description'],
                    facebook: hash_place['facebook'],
                    instagram: hash_place['instagram'],
                    json: json)
      @place.save
      flash[:success] = "Place added successfully!"
      redirect_to place_path(@place)
    rescue
      flash[:danger] = "The JSON text provided was in a wrong format. \n The right format is."
      redirect_to addplace_path
    end
  end

  def show
    @place = Place.find(params[:id])
  end

  def edit
  end

  def destroy
    place = Place.find(params[:id])
    place.destroy
    flash[:success] = "Place '#{place.name}' deleted"
    redirect_to places_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title = '')
    base_title = 'CUbNEt'
    if page_title.blank?
      base_title
    else
      page_title + ' | ' + base_title
    end
  end
  
end

app/helpers/information_pages_helper.rb
module InformationPagesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/information_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>About</h1>
<p>
  Here goes the about information:
</p>
<p>
  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</p>
<p>
  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</p>
<p>
  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</p>

app/views/information_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  This app has been developed for help you organize your favorites places.
</p>
<p>
  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</p>
<p>
  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</p>
<p>
  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</p>

app/views/information_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  Here goes all the help that you can get:
</p>
<p>
  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna
  aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis
  aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat
  cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</p>
<p>
  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna
  aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis
  aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat
  cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</p>
<p>
  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna
  aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis
  aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat
  cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</p>

app/views/information_pages/home.html.erb
<% provide(:title, 'Home') %>
<div class="center jumbotron">
  <h1>Welcome to CUbNEt</h1>

  <h2>
    This is the home page for the CUbNEt app, if you want to see all the Places
    and information that we can offer visit our places page.
    There you can find all sort of Houses, Schools and Companies with detail
    descriptions, and you can also add a place of your like.
  </h2>

  <%= link_to "See places now!", places_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href= "<%= root_path %>" >CUbNEt</a>
    by Gelin Eguinosa
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "CUbNEt", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "Help",   help_path %></li>
        <li><%= link_to "Places", places_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title (yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/places/edit.html.erb
<h1>Places#edit</h1>
<p>Find me in app/views/places/edit.html.erb</p>

app/views/places/index.html.erb
<% provide(:title, 'Places') %>
<div class="row">
  <aside class="col-md-4">
    <section>
      <h1>Add Place</h1>
    </section>
    <section>
      <h4>
        If you want to add a place to this site, you have to provide all the
        information in JSON format.
      </h4>
      <h4>
        Our site has already <%= pluralize(@places.count, "place") %>
      </h4>
    </section>
    <section class="add_json">
      <%= link_to "Add JSON", addplace_path, class: "btn btn-primary" %>
    </section>
  </aside>
  <div class="col-md-8">
    <h1>All Places (<%= @places.count %>)</h1>
    <%= will_paginate %>
    <ol class="places">
      <% @places.each do |place| %>
        <li id="place-<%= place.id %>">
          <span class="place"><%= link_to place.name, place %></span>
          <span class="description">
            <%= place.description.split('').take(80).join %>...
          </span>
          <span class="timestamp">
            Posted <%= time_ago_in_words(place.created_at) %> ago.
            <%= link_to "delete", place, method: :delete, data: { confirm: "You sure?" } %>
          </span>
        </li>
      <% end %>
    </ol>
    <%=  will_paginate %>
  </div>
</div>

app/views/places/new.html.erb
<% provide(:title, 'Add Place') %>
<h1>Add Place</h1>

<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <%= form_for(@place) do |f| %>
      <%= f.label :JSON %>
      <%= f.text_area :json, placeholder: @placeholder %>

      <%= f.submit "Submit JSON", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/places/show.html.erb
<% provide(:title, @place.name) %>
<h1><%= @place.name %></h1>
<h5>
  Find us on
  <%= link_to "Facebook", @place.facebook, target: "_blank" %>.
</h5>
<h5>
  Find us on
  <%= link_to "Instagram", @place.instagram, target: "_blank" %>.
</h5>
<p>
  <%= @place.description %>
</p>
<h5>
  If you don't like this place or the description, you can
  <%= link_to "delete it", @place, method: :delete, data: { confirm: "You sure?" } %>
</h5>